FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
COPY [".certs", "/certs"]

WORKDIR /src
COPY ["Services/Services.Common/Services.Common.csproj", "Services/Services.Common/"]
RUN dotnet restore "Services/Services.Common/Services.Common.csproj"
COPY . .
WORKDIR "/src/Services/Services.Common"
RUN dotnet build "Services.Common.csproj" -c Release -o /app/build

WORKDIR /src
COPY ["Infrastructure/Infrastructure.csproj", "Infrastructure/"]
RUN dotnet restore "Infrastructure/Infrastructure.csproj"
COPY . .
WORKDIR "/src/Infrastructure"
RUN dotnet build "Infrastructure.csproj" -c Release -o /app/build

WORKDIR /src
COPY ["Services/CourseContentManagement/CourseContentManagement.csproj", "Services/CourseContentManagement/"]
RUN dotnet restore "Services/CourseContentManagement/CourseContentManagement.csproj"
COPY . .
WORKDIR "/src/Services/CourseContentManagement"
RUN dotnet build "CourseContentManagement.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CourseContentManagement.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM publish AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--filter", "**/*.cs"]

